# Generated by Django 5.2.8 on 2025-12-11 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='samplemodel',
            old_name='address',
            new_name='father_name',
        ),
    ]
