# Generated by Django 5.2.8 on 2025-12-11 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp1', '0002_rename_address_samplemodel_father_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplemodel',
            name='address',
            field=models.TextField(default='Dhaka'),
        ),
        migrations.AlterField(
            model_name='samplemodel',
            name='father_name',
            field=models.TextField(default='Rahim'),
        ),
    ]
